language: csharp
solution: ./GladNet.Lidgren.sln

install:
  - nuget install NUnit.Runners -Version 3.0.1 -OutputDirectory tests/testrunner
  - nuget restore GladNet.Lidgren.sln -ConfigFile NuGet.config

notifications:
  slack: boomanationteam:sPQHUqEWA3wTaB9IKOSxe2f1

before_script:
  - chmod +x ./tests/RunTests.sh
  - chmod +x ./Build.sh

script:
  - cd "$TRAVIS_BUILD_DIR"
  - ./Build.sh
  - cd "$TRAVIS_BUILD_DIR/tests"
  - ./RunTests.sh
  - cd "$TRAVIS_BUILD_DIR"