language: csharp
solution: ./GladNet2.Lidgren.sln

before_install:
  - git submodule update --init --recursive

install:
  - nuget install NUnit.Runners -Version 3.0.1 -OutputDirectory tests/testrunner
  - nuget restore GladNet2.Lidgren.sln

before_script:
  - chmod +x ./lib/BuildDependencies.sh
  - chmod +x ./tests/RunTests.sh
  - chmod +x ./Build.sh

script:
  - cd "$TRAVIS_BUILD_DIR/lib"
  - ./BuildDependencies.sh
  - cd "$TRAVIS_BUILD_DIR"
  - ./Build.sh
  - cd "$TRAVIS_BUILD_DIR/tests"
  - ./RunTests.sh
  - cd "$TRAVIS_BUILD_DIR"